services:
  redis:
    image: 'redis:alpine'

  tester:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ['npm', 'run', 'test:e2e:docker']
